//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReciboGG.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maestra()
        {
            this.Gradoes = new HashSet<Grado>();
        }
    
        public long Id_Maestra { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<long> DPI { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grado> Gradoes { get; set; }
    }
}
