//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReciboGG.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecibosGGEntities : DbContext
    {
        public RecibosGGEntities()
            : base("name=RecibosGGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Grado> Gradoes { get; set; }
        public virtual DbSet<Maestra> Maestras { get; set; }
        public virtual DbSet<Pago_Detalle> Pago_Detalle { get; set; }
        public virtual DbSet<Recibo> Reciboes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Tutor> Tipo_Tutor { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
    }
}
