//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReciboGG.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutor()
        {
            this.Alumnoes = new HashSet<Alumno>();
            this.Reciboes = new HashSet<Recibo>();
        }
    
        public long Id_Tutor { get; set; }
        //public long Id_Alumno { get; set; }
        public long Id_Tipo_Tutor { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<long> DPI { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno> Alumnoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibo> Reciboes { get; set; }
        public virtual Tipo_Tutor Tipo_Tutor { get; set; }
    }
}
